# Generated by Django 4.0.4 on 2022-05-26 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_reviewrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='create_dete',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_avaliable',
            new_name='is_available',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='modify_dete',
            new_name='modify_date',
        ),
    ]
